export const computerChinese: Record<string, { title: string; summary: string; eyebrow: string; sections: { heading: string; body: string }[]; exercises: Record<string, { title: string; prompt: string; hints: string[] }> }> = {
  overview: { title: '考试地图', summary: '先弄清科目、题型和自己的学习路线。', eyebrow: '入门导航', sections: [{ heading: '计算机二级考什么', body: '不同科目会围绕选择题、操作题或程序设计题展开。备考第一步不是盲目刷题，而是先确认报考科目、考试大纲和软件环境。' }, { heading: '建议的学习顺序', body: '先补公共基础，再熟悉软件或语言的基本操作，最后按题型限时练习。每次练习都记录错因，而不只记答案。' }], exercises: {} },
  basics: { title: '公共基础：计算机基础', summary: '先弄懂信息、硬件、软件和操作系统这些高频概念。', eyebrow: '公共基础', sections: [{ heading: '信息与单位', body: '计算机用二进制表示数据。bit 是最小的信息单位，8 bit = 1 Byte；KB、MB、GB 常按 1024 倍递进。容量、内存和网络传输速度是不同概念，看到单位要先判断题目在问什么。' }, { heading: '系统与应用', body: 'CPU、内存、外存和输入输出设备属于硬件；操作系统负责管理硬件和提供运行环境；浏览器、文字处理软件和表格软件属于应用软件。按“谁管理资源、谁完成具体任务”可以快速区分。' }], exercises: {} },
  network: { title: '公共基础：网络与安全', summary: '理解上网、传输和保护信息时各个概念的作用。', eyebrow: '公共基础', sections: [{ heading: '网络术语', body: 'IP 地址用于标识网络中的设备，域名是便于人阅读的名称，DNS 负责把域名解析为 IP。HTTP/HTTPS 是访问 Web 资源时常见的协议，HTTPS 在传输过程中提供加密和身份校验能力。' }, { heading: '安全思维', body: '安全问题要看风险和措施是否匹配：强密码和多因素认证降低账号被猜中的风险；备份应对数据丢失；杀毒和更新降低恶意软件利用漏洞的风险；不点击可疑链接可以减少钓鱼风险。' }], exercises: {} },
  foundations: { title: '公共基础：数据与算法', summary: '用最少的概念建立做选择题所需的基础。', eyebrow: '公共基础', sections: [{ heading: '数据结构', body: '线性结构强调元素之间的前后关系；树和图用于表达层级或网络关系。遇到题目时先判断数据之间的关系，再选择结构。' }, { heading: '算法复杂度', body: '复杂度用于描述输入规模变大时资源消耗如何增长。备考中要能辨认常见的 O(1)、O(n) 和 O(n²) 级别。' }], exercises: {} },
  word: { title: 'Word：文档排版基础', summary: '掌握样式、段落和页面设置，少靠手动堆格式。', eyebrow: 'MS OFFICE', sections: [{ heading: '先结构，后外观', body: '标题使用内置标题样式，正文使用正文样式；不要靠连续空格和回车模拟排版。这样目录、导航和统一修改才能正常工作。' }, { heading: '操作题思路', body: '先保存文件，再处理页面设置、样式和内容，最后检查分页、编号与格式要求。每完成一类要求就核对一次。' }], exercises: {} },
  excel: { title: 'Excel：公式与数据', summary: '从单元格引用、函数和排序筛选开始。', eyebrow: 'MS OFFICE', sections: [{ heading: '公式从等号开始', body: 'Excel 公式通常以 = 开始。相对引用会随复制变化，绝对引用使用 $ 锁定行或列，混合引用只锁定其中一部分。' }, { heading: '先确认数据范围', body: '使用 SUM、AVERAGE、COUNTIF 等函数前，先确认数据区域和条件。排序前要选中完整数据区域，避免只排了一列。' }], exercises: {} },
  powerpoint: { title: 'PowerPoint：信息表达', summary: '让一页幻灯片只表达一个清晰重点。', eyebrow: 'MS OFFICE', sections: [{ heading: '内容要有层次', body: '标题说明主题，正文承载少量关键信息，图表或图片服务于观点。不要把整段讲稿原样塞进幻灯片。' }, { heading: '母版与统一格式', body: '重复出现的字体、页脚和版式应优先通过母版或主题统一设置，再处理个别页面。' }], exercises: {} },
  python: { title: 'Python：程序设计入门', summary: '从“看懂一行”开始，建立变量、类型、分支、循环和函数之间的完整联系。', eyebrow: '程序设计', sections: [{ heading: '先把代码翻译成人话', body: '读 Python 题时先不要急着背关键字。把每行问成三个问题：它读取了什么？它改变了哪个变量？它什么时候输出？例如 total = 0 是准备一个累加器，for 是让同一段代码重复执行，total += number 是每轮更新状态。' }, { heading: '缩进决定代码属于谁', body: 'Python 不用大括号包围代码块，而是依靠缩进表达层级。if、for、while、def 后面要写冒号，下一层通常缩进 4 个空格；同一层必须保持一致。少一个缩进可能是语法错误，多一个缩进可能让语句只在某个分支或循环里执行。' }, { heading: '变量的类型会影响结果', body: 'input() 得到字符串，所以输入 2 和 3 后直接写 input() + input() 得到的是字符串拼接“23”，不是数字 5。需要计算时写 int(input())；需要小数时写 float(input())。看到 + 时先确认两边到底是文本还是数字。' }, { heading: '用追踪表检查循环', body: '手算循环时画四列：轮次、当前变量、更新前的结果、更新后的结果。range(1, 4) 只产生 1、2、3，结束值不包含；判断“至少 60 分”要写 >= 60。把 0、1、59、60、61 放进测试，往往比再看一遍答案更有效。' }, { heading: '函数不是魔法', body: 'def 先定义一个可复用的步骤，调用函数时才真正执行。参数是输入，return 是交还给调用者的结果，print 只是把内容显示出来。一个函数最好只做一件事，并且能用两个普通例子和一个边界例子单独验证。' }, { heading: '跟着做', body: '先写出输入、处理、输出，再用小数据手算一遍。补全代码后检查每个冒号、括号和缩进；循环题逐轮记录变量；函数题分别测试正常值和边界值。' }, { heading: '常见失分点', body: '把 = 和 == 混淆；把 input() 当成数字；把 range 的结束值算进去；把 print 当成 return；只测试一个例子，漏掉 0、59、60、空列表等边界。' }], exercises: {} },
  practice: { title: '刷题与复盘', summary: '把做题变成可重复、可改进的训练。', eyebrow: '备考方法', sections: [{ heading: '三遍练习法', body: '第一遍看懂题目和操作目标，第二遍独立完成并计时，第三遍只针对错题重做。重复练习时要改变顺序，确认自己掌握的是方法。' }, { heading: '错题记录', body: '至少记录题型、错误原因、正确操作和下次提醒。若同一类错误重复出现，就把它加入下一次专项练习。' }], exercises: {} },
}
