export const computerChinese: Record<string, { title: string; summary: string; eyebrow: string; sections: { heading: string; body: string }[]; exercises: Record<string, { title: string; prompt: string; hints: string[] }> }> = {
  overview: { title: '考试地图', summary: '先弄清科目、题型和自己的学习路线。', eyebrow: '入门导航', sections: [{ heading: '计算机二级考什么', body: '不同科目会围绕选择题、操作题或程序设计题展开。备考第一步不是盲目刷题，而是先确认报考科目、考试大纲和软件环境。' }, { heading: '建议的学习顺序', body: '先补公共基础，再熟悉软件或语言的基本操作，最后按题型限时练习。每次练习都记录错因，而不只记答案。' }], exercises: {} },
  foundations: { title: '公共基础：数据与算法', summary: '用最少的概念建立做选择题所需的基础。', eyebrow: '公共基础', sections: [{ heading: '数据结构', body: '线性结构强调元素之间的前后关系；树和图用于表达层级或网络关系。遇到题目时先判断数据之间的关系，再选择结构。' }, { heading: '算法复杂度', body: '复杂度用于描述输入规模变大时资源消耗如何增长。备考中要能辨认常见的 O(1)、O(n) 和 O(n²) 级别。' }], exercises: {} },
  word: { title: 'Word：文档排版基础', summary: '掌握样式、段落和页面设置，少靠手动堆格式。', eyebrow: 'MS OFFICE', sections: [{ heading: '先结构，后外观', body: '标题使用内置标题样式，正文使用正文样式；不要靠连续空格和回车模拟排版。这样目录、导航和统一修改才能正常工作。' }, { heading: '操作题思路', body: '先保存文件，再处理页面设置、样式和内容，最后检查分页、编号与格式要求。每完成一类要求就核对一次。' }], exercises: {} },
  excel: { title: 'Excel：公式与数据', summary: '从单元格引用、函数和排序筛选开始。', eyebrow: 'MS OFFICE', sections: [{ heading: '公式从等号开始', body: 'Excel 公式通常以 = 开始。相对引用会随复制变化，绝对引用使用 $ 锁定行或列，混合引用只锁定其中一部分。' }, { heading: '先确认数据范围', body: '使用 SUM、AVERAGE、COUNTIF 等函数前，先确认数据区域和条件。排序前要选中完整数据区域，避免只排了一列。' }], exercises: {} },
  powerpoint: { title: 'PowerPoint：信息表达', summary: '让一页幻灯片只表达一个清晰重点。', eyebrow: 'MS OFFICE', sections: [{ heading: '内容要有层次', body: '标题说明主题，正文承载少量关键信息，图表或图片服务于观点。不要把整段讲稿原样塞进幻灯片。' }, { heading: '母版与统一格式', body: '重复出现的字体、页脚和版式应优先通过母版或主题统一设置，再处理个别页面。' }], exercises: {} },
  python: { title: 'Python：程序设计入门', summary: '读懂变量、分支、循环和函数的基本形状。', eyebrow: '程序设计', sections: [{ heading: '执行顺序', body: '程序默认从上到下执行。if 根据条件选择路径，for 或 while 重复执行，函数把可复用的逻辑封装起来。' }, { heading: '做题方法', body: '先读输入和输出，再画出变量变化；遇到循环逐轮记录关键变量。不要只凭直觉猜结果。' }], exercises: {} },
  practice: { title: '刷题与复盘', summary: '把做题变成可重复、可改进的训练。', eyebrow: '备考方法', sections: [{ heading: '三遍练习法', body: '第一遍看懂题目和操作目标，第二遍独立完成并计时，第三遍只针对错题重做。重复练习时要改变顺序，确认自己掌握的是方法。' }, { heading: '错题记录', body: '至少记录题型、错误原因、正确操作和下次提醒。若同一类错误重复出现，就把它加入下一次专项练习。' }], exercises: {} },
}
