export interface ChineseExerciseCopy { title: string; prompt: string; hints: string[] }
export interface ChineseLessonCopy { sections: { heading: string; body: string }[]; note?: string; exercises: Record<string, ChineseExerciseCopy> }
const h = (title: string, prompt: string, hints: string[]): ChineseExerciseCopy => ({ title, prompt, hints })
export const tomlChinese: Record<string, ChineseLessonCopy> = {
  intro: { sections: [{ heading: '为什么是 TOML？', body: 'TOML 是 Tom 的明显、极简语言，专门为人类读写而设计，同时让程序可以精确解析。' }, { heading: '你会在哪里见到它', body: '项目元数据、构建工具和应用设置经常使用 TOML。Python 项目使用 pyproject.toml，Rust 项目使用 Cargo.toml。' }], note: 'TOML 是配置格式，不是通用编程语言。', exercises: { 'intro-1': h('第一个配置', '创建一个名为 demo 的项目。', ['先看键的名字。', '文本值需要引号，数字和布尔值不需要。', '参考示例，再按题目改写。']), 'intro-2': h('修复配置', '修复缺少引号的问题。', ['文本值需要引号。', '裸单词不是合法的 TOML 值。', '使用基本字符串语法："文本"。']), 'intro-3': h('添加版本', '创建 name = "app" 和 version = "1.0.0"。', ['一个设置占一行。', '两个值都是字符串。', '字符串必须放在双引号中。']) } },
  'key-value': { sections: [{ heading: '赋值的形状', body: '键用来识别设置，等号把键和值分开。等号两边的空格是可选的，但保留空格更容易阅读。' }, { heading: '注释', body: '# 会开始一条注释，直到当前行结束。注释用于解释意图，不会进入解析后的数据。' }], exercises: { 'kv-1': h('启用服务', '设置 enabled = true。', ['这是一个布尔值。', '布尔值不需要引号。', '值必须是小写的 true。']), 'kv-2': h('修复键和值', '修复分隔符和字符串值。', ['TOML 使用 =，不是 :。', 'api 是字符串。', '重新检查解析结果。']), 'kv-3': h('写出两个设置', '创建 debug = false 和 retries = 3。', ['false 是布尔值。', '3 是整数。', '每个设置各占一行。']) } },
  types: { sections: [{ heading: '一组清晰的类型', body: '字符串、整数、小数、布尔值、日期和时间都是不同的值。这让读取配置的程序行为更加可预测。' }, { heading: '观察值的写法', body: '引号表示文本，小数点表示浮点数，true 和 false 是布尔值，而不是字符串。' }], exercises: { 'types-1': h('混合使用类型', '创建 count = 3 和 ratio = 1.5。', ['整数没有小数点。', '小数点后的值是浮点数。', '不要给数字加引号。']), 'types-2': h('修复布尔值', '让 active 成为布尔值，而不是文本。', ['移除引号。', '布尔字面量使用小写。', '解析后的值应该是 true，而不是字符串 "true"。']), 'types-3': h('描述一次构建', '创建 name = "release" 和 ready = false。', ['name 是字符串。', 'ready 是布尔值。', '注意两种值的写法不同。']) } },
  string: { sections: [{ heading: '基本字符串和字面字符串', body: '基本字符串使用双引号，并支持 \\n 等转义。字面字符串使用单引号，可以让反斜杠保持原样。' }, { heading: '多行字符串', body: '三重引号可以容纳跨行文本，适合描述信息或嵌入代码片段。' }], exercises: { 'str-1': h('写一句问候', '创建 greeting = "hello"。', ['这是一个字符串。', '使用双引号包住 hello。', '不要忘记键和值之间的等号。']), 'str-2': h('修复字符串', '修复没有结束引号的字符串。', ['基本字符串需要开头和结尾两个双引号。', '让 hello 保持在引号内。', '编辑后再次点击检查答案。']), 'str-3': h('保存路径', '创建 path = "./data"。', ['路径也是字符串。', '使用双引号。', '反斜杠和引号需要特别注意。']) } },
  number: { sections: [{ heading: '数字是值', body: '整数没有小数点，浮点数有小数点。数字可以使用 + 或 - 符号，也可以用下划线作为视觉分隔。' }, { heading: '保持含义不变', body: '1_000 与 1000 是同一个数字。加上引号会把数字变成文本，工具的处理方式也会随之改变。' }], exercises: { 'num-1': h('设置端口', '创建 port = 8080。', ['端口是整数。', '不要添加引号。', '键和值之间使用等号。']), 'num-2': h('修复数字', '让 timeout 成为数字。', ['移除数字两边的引号。', '带小数点的是浮点数。', '期望值是 2.5。']), 'num-3': h('设置限制', '创建 limit = -10。', ['负号可以直接写在数字前。', '这仍然是一个整数。', '不要使用字符串引号。']) } },
  boolean: { sections: [{ heading: '只有两个值', body: 'TOML 的布尔值是 true 和 false。它们必须使用小写，并且不能放在引号中。' }], exercises: { 'bool-1': h('打开功能', '设置 enabled = true。', ['这是开关值。', '移除引号。', '使用小写 true。']), 'bool-2': h('修复 debug', '让 debug 成为布尔值 false。', ['移除引号。', '使用小写 false。', '不要把布尔值写成字符串。']), 'bool-3': h('写出功能开关', '创建 beta = true 和 logs = false。', ['两个值都是布尔值。', '每个设置各占一行。', '布尔值不使用引号。']) } },
  array: { sections: [{ heading: '一个有序列表', body: '数组使用方括号和逗号。数组可以跨多行，也可以包含字符串、数字或嵌套数组。' }, { heading: '类型要保持一致', body: '让数组中的项目保持兼容。端口列表应该包含数字，主机列表应该包含字符串。' }], exercises: { 'arr-1': h('列出端口', '创建包含 80 和 443 的 ports 数组。', ['数组使用方括号。', '项目之间用逗号分隔。', '两个端口都是数字。']), 'arr-2': h('修复数组', '修复缺少结束方括号的问题。', ['数组以 [ 开始，以 ] 结束。', '项目之间需要逗号。', '确认解析后的值是列表。']), 'arr-3': h('写出支持格式', '创建 formats = ["json", "toml"]。', ['这是字符串数组。', '每个字符串都需要引号。', '不要忘记逗号。']) } },
  table: { sections: [{ heading: '表是一个命名空间', body: '[server] 这样的表头会打开一个命名空间。之后的键属于 server，直到声明另一个表。' }, { heading: '为什么需要表', body: '表可以把扁平设置组织成有意义的树。解析结果会是 { server: { ... } }，与应用理解配置的方式一致。' }], exercises: { 'table-1': h('创建服务器', '创建一个 [server] 表，并设置 port = 8080。', ['表头放在方括号中。', '把 port 写在表头之后。', 'port 是整数。']), 'table-2': h('修复表', '修复表头。', ['表头需要左右两个方括号。', '键值写在表头之后。', 'localhost 是字符串。']), 'table-3': h('描述应用', '创建 [app]，并设置 name = "web"。', ['先声明 app 表。', 'name 是字符串。', '使用双引号。']) } },
  nested: { sections: [{ heading: '点号路径', body: '[database.primary] 会创建 database，再在其中创建 primary。这是表达嵌套对象的简洁方式。' }], exercises: { 'nested-1': h('连接数据库', '创建 [database.primary]，并设置 port = 5432。', ['嵌套表使用点号。', '表头需要完整写出。', 'port 是整数。']), 'nested-2': h('修复路径', '修复嵌套表头。', ['嵌套表名使用点号。', '不要在表头中使用逗号。', '结果应该有两层对象。']), 'nested-3': h('添加副本', '创建 [database.replica]，并设置 host = "replica"。', ['replica 是 primary 的同级表。', '使用点号表达层级。', 'host 是字符串。']) } },
  'array-table': { sections: [{ heading: '对象列表', body: '[[servers]] 会在数组中开始一张表。重复这个表头，就会向同一个列表添加另一个对象。' }, { heading: '把它看成记录', body: '服务器、用户或插件都可以用这种结构表示：每个重复的代码块描述一个形状相同的项目。' }], exercises: { 'aot-1': h('添加两台服务器', '创建两个名称分别为 a 和 b 的服务器。', ['使用双层方括号。', '第二条记录重复同一个表头。', '解析后的值应该是数组。']), 'aot-2': h('修复记录', '把第二张表改成 servers 数组中的另一个项目。', ['两个代码块都是列表项目。', '两次使用 [[servers]]。', '单层方括号创建的是对象，不是列表。']), 'aot-3': h('写出服务列表', '创建两个名称分别为 api 和 web 的服务。', ['重复使用 [[services]]。', '每个项目都有 name。', '项目之间可以空一行。']) } },
  inline: { sections: [{ heading: '紧凑对象', body: '内联表使用花括号和逗号分隔的键值对，适合小型、独立的结构。' }], exercises: { 'inline-1': h('创建坐标点', '创建 point，其中 x = 1、y = 2。', ['内联表使用花括号。', '字段之间用逗号分隔。', 'x 和 y 都是数字。']), 'inline-2': h('修复内联表', '补上缺少的结束花括号。', ['内联表以 { 开始，以 } 结束。', '字段之间需要逗号。', '保持 x 和 y 为数字。']), 'inline-3': h('写出尺寸', '创建 size，其中 width = 10、height = 20。', ['这是一个内联表。', '两个字段都放在花括号内。', '字段之间使用逗号。']) } },
  datetime: { sections: [{ heading: '四种时间类型', body: 'TOML 支持带时区的日期时间、本地日期时间、本地日期和本地时间。使用 ISO 8601 风格可以让工具正确理解它们。' }], exercises: { 'date-1': h('添加日期', '创建 birthday = 1990-01-01。', ['这是 TOML 的日期值。', '不要加引号。', '按年-月-日书写。']), 'date-2': h('修复日期', '移除日期两边的引号。', ['TOML 有原生日期和时间值。', '移除引号。', '保持日期和时间的 ISO 风格。']), 'date-3': h('安排发布', '创建 release = 2024-06-01。', ['使用日期类型。', '不要加引号。', '月份和日期都保留两位数字。']) } },
  style: { sections: [{ heading: '注释解释原因', body: '用注释记录背景、取舍和安全默认值。不要只重复键名本身。' }, { heading: '保持格式一致', body: '等号两边留空格，把相关键放在一起，并按照合理顺序排列表。' }], exercises: { 'style-1': h('添加注释', '创建 port = 8080，注释可选。', ['注释以 # 开头。', '注释不会成为数据。', '设置本身仍然需要合法的键和值。']), 'style-2': h('修复格式', '让这段配置有效。', ['行内注释是允许的。', '每个设置占一行。', '注释不会进入解析结果。']), 'style-3': h('写出可读配置', '创建 name = "demo" 和 version = "1.0"。', ['两个值都是字符串。', '使用双引号。', '每个设置各占一行。']) } },
  errors: { sections: [{ heading: '常见陷阱', body: '注意重复键、重复定义的表、未结束的字符串、数组类型混用以及缺少引号。' }, { heading: '格式容易混淆', body: 'TOML 使用等号和表头；YAML 常使用冒号；JSON 要求引号和花括号。它们看起来相似，但语法不能混用。' }], exercises: { 'err-1': h('修复引号', '修复缺少引号和括号的问题。', ['字符串需要引号。', '表头本身已经正确。', '保持 port 为数字。']), 'err-2': h('修复重复键', '只保留一个值为 demo 的 name 键。', ['一个键只能定义一次。', '删除重复的那一行。', '最终值应该是 demo。']), 'err-3': h('构建有效配置', '创建 [server]，并设置 host = "localhost"。', ['先声明 server 表。', 'host 是字符串。', '使用双引号包住 localhost。']) } },
  pyproject: { sections: [{ heading: '项目元数据', body: 'pyproject.toml 为工具提供一个标准位置，用来发现项目名称、版本、描述和依赖。' }, { heading: '工具配置', body: '[tool] 命名空间为不同工具提供独立的配置空间。脚本则把命令名映射到 Python 可调用对象。' }], note: '本课关注结构和基本思想，不展开所有打包细节。', exercises: { 'py-1': h('添加项目元数据', '创建 [project]，并设置 name 和 version。', ['先打开 project 表。', '添加两个字符串值。', '把示例当作结构参考。']), 'py-2': h('修复脚本', '修复 project.scripts 表头和脚本值。', ['可调用路径是文本。', '给 example:main 加引号。', '点号表头会创建嵌套表。']), 'py-3': h('描述你的包', '创建 [project]，设置 name = "demo" 和 description = "A demo"。', ['先创建 project 表。', '两个值都是字符串。', '长文本同样需要引号。']) } },
}
