import { useEffect, useMemo, useState } from 'react'
import CodeMirror from '@uiw/react-codemirror'
import { langs } from '@uiw/codemirror-extensions-langs'
import { oneDark } from '@codemirror/theme-one-dark'
import { Check, ChevronDown, ChevronRight, CircleCheck, Code2, Globe2, Info, Lightbulb, Menu, Moon, RotateCcw, Sun, Terminal, X } from 'lucide-react'
import { tomlModule } from './languages/toml/config'
import { tomlChinese } from './languages/toml/i18n'
import { computerModule } from './languages/computer/config'
import { computerChinese } from './languages/computer/i18n'
import { parseToml } from './core/validator'
import type { Exercise } from './core/types'
import './styles.css'

const STORAGE_KEY = 'syntaxlab-progress-v1'
type Locale = 'zh' | 'en'
type Progress = { lessonId: string; completedLessons: string[]; completedExercises: string[]; dark: boolean; locale: Locale }
const browserLocale: Locale = typeof navigator !== 'undefined' && navigator.language.toLowerCase().startsWith('zh') ? 'zh' : 'en'
const defaultProgress: Progress = { lessonId: 'intro', completedLessons: [], completedExercises: [], dark: true, locale: browserLocale }
function loadProgress(): Progress { try { const stored = JSON.parse(localStorage.getItem(STORAGE_KEY) ?? '{}') as Partial<Progress>; return { ...defaultProgress, ...stored, locale: stored.locale ?? browserLocale } } catch { return defaultProgress } }
const copy = {
  zh: { path: '学习路径', practice: '练习', write: '自己写出来', example: '示例', lessons: '课', exercises: '练习', reset: '重置进度', complete: '完成本课', completed: '本课已完成', check: '检查答案', resetAnswer: '重置', correct: '正确，做得好。', structure: '结构还不符合这道练习。', explore: '探索更多模块', soon: '学习专栏', soonDetail: 'TOML · 计算机二级入门', about: '关于', close: '关闭', aboutTitle: '关于 SyntaxLab', aboutBody: 'SyntaxLab 是一个面向开发者和考生的交互式学习工作台。通过阅读、编写、犯错和反馈，真正理解语法、工具与计算机基础。', aboutDetail: '当前内容：TOML / 计算机二级入门 · 数据保存在你的浏览器中 · 开源项目', lang: 'English', completeExample: '补全示例', repair: '找出并修复错误', create: '按要求编写' },
  en: { path: 'LEARNING PATH', practice: 'PRACTICE', write: 'Write it yourself', example: 'Example', lessons: 'lessons', exercises: 'exercises', reset: 'Reset progress', complete: 'Mark lesson complete', completed: 'Lesson complete', check: 'Check answer', resetAnswer: 'Reset', correct: 'Correct. Nice work.', structure: 'The structure does not match this exercise yet.', explore: 'Explore modules', soon: 'More syntax, soon.', soonDetail: 'YAML · Markdown · C · Python', about: 'About', close: 'Close', aboutTitle: 'About SyntaxLab', aboutBody: 'SyntaxLab is an interactive learning workspace for developers. Read, write, make mistakes, and build a real understanding of syntax.', aboutDetail: 'Current module: TOML · Data stays in your browser · Open source project', lang: '中文', completeExample: 'Complete the example', repair: 'Find and fix the error', create: 'Write from a requirement' },
} as const
const lessonZh: Record<string, { title: string; summary: string; eyebrow: string }> = {
  intro: { title: 'TOML 是什么？', summary: '一种平静、易读的配置格式。', eyebrow: '从这里开始' }, 'key-value': { title: '键 / 值', summary: '每个设置都从一个名字和一个值开始。', eyebrow: '基础' }, types: { title: '数据类型', summary: 'TOML 拥有明确而实用的基础类型。', eyebrow: '基础' }, string: { title: '字符串', summary: '安全地表示文本，包括引号和换行。', eyebrow: '值' }, number: { title: '数字', summary: '整数、小数、正负号与可读的分隔符。', eyebrow: '值' }, boolean: { title: '布尔值', summary: '用两个词表达开关状态。', eyebrow: '值' }, array: { title: '数组', summary: '把相关值按可预测的顺序放在一起。', eyebrow: '结构' }, table: { title: '表', summary: '把相关键归到一个命名空间下。', eyebrow: '结构' }, nested: { title: '嵌套表', summary: '用更深的配置路径表达层级结构。', eyebrow: '结构' }, 'array-table': { title: '表数组', summary: '用双中括号表示重复的记录。', eyebrow: '结构' }, inline: { title: '内联表', summary: '让小型对象紧挨着使用它的键。', eyebrow: '结构' }, datetime: { title: '日期 / 时间', summary: '用标准形式保存时间点和日历日期。', eyebrow: '值' }, style: { title: '注释与格式', summary: '让配置文件方便下一个人维护。', eyebrow: '练习' }, errors: { title: '常见错误', summary: '学会读懂解析器反馈并修复数据结构。', eyebrow: '调试' }, pyproject: { title: 'pyproject.toml', summary: '用 TOML 描述一个真实的 Python 项目。', eyebrow: '真实场景' },
}
function friendlyError(error: string | undefined, locale: Locale): string {
  if (!error) return locale === 'zh' ? 'TOML 结构还不正确，请继续检查。' : 'The TOML structure is not correct yet.'
  if (locale === 'en') return error
  if (/unterminated|string/i.test(error)) return '字符串没有正确结束，请检查开头和结尾的引号。'
  if (/duplicate|already defined/i.test(error)) return '发现重复的键或表定义；同一个键只能定义一次。'
  if (/expected.*\]|bracket|table/i.test(error)) return '表头或数组括号不完整，请检查 [ ] 或 [[ ]]。'
  if (/expected.*value|invalid.*value/i.test(error)) return '这里的值格式不正确，请检查等号、引号和布尔值写法。'
  return `TOML 语法有误：${error}`
}
function App() {
  const [progress, setProgress] = useState<Progress>(loadProgress)
  const [moduleId, setModuleId] = useState('toml')
  const [selectedId, setSelectedId] = useState(progress.lessonId)
  const [mobileNav, setMobileNav] = useState(false)
  const [showModules, setShowModules] = useState(false)
  const [showAbout, setShowAbout] = useState(false)
  const activeModule = moduleId === computerModule.id ? computerModule : tomlModule
  const selected = useMemo(() => activeModule.lessons.find((lesson) => lesson.id === selectedId) ?? activeModule.lessons[0], [activeModule, selectedId])
  useEffect(() => { localStorage.setItem(STORAGE_KEY, JSON.stringify(progress)); document.documentElement.dataset.theme = progress.dark ? 'dark' : 'light' }, [progress])
  const t = copy[progress.locale]
  const completedCount = activeModule.lessons.filter((lesson) => progress.completedLessons.includes(`${activeModule.id}:${lesson.id}`) || (activeModule.id === 'toml' && progress.completedLessons.includes(lesson.id))).length
  const completedExercises = activeModule.lessons.flatMap((lesson) => lesson.exercises).filter((exercise) => progress.completedExercises.includes(exercise.id)).length
  const currentCopy = progress.locale === 'zh' && activeModule.id === 'toml' ? lessonZh[selected.id] : undefined
  const localized = progress.locale === 'zh' && activeModule.id === 'toml' ? tomlChinese[selected.id] : undefined
  const computerCopy = progress.locale === 'zh' && activeModule.id === computerModule.id ? computerChinese[selected.id] : undefined
  const visibleExercises = selected.exercises.map((exercise) => localized?.exercises[exercise.id] ? { ...exercise, ...localized.exercises[exercise.id] } : exercise)
  const lessonKey = `${activeModule.id}:${selected.id}`
  const isLessonComplete = progress.completedLessons.includes(lessonKey) || (activeModule.id === 'toml' && progress.completedLessons.includes(selected.id))
  const selectLesson = (id: string) => { setSelectedId(id); setProgress((p) => ({ ...p, lessonId: id })); setMobileNav(false) }
  const selectModule = (id: string) => { const next = id === computerModule.id ? computerModule : tomlModule; setModuleId(next.id); setSelectedId(next.lessons[0].id); setProgress((p) => ({ ...p, lessonId: next.lessons[0].id })); setMobileNav(false) }
  const markLesson = () => setProgress((p) => ({ ...p, completedLessons: isLessonComplete ? p.completedLessons : [...p.completedLessons, lessonKey] }))
  const toggleLocale = () => setProgress((p) => ({ ...p, locale: p.locale === 'zh' ? 'en' : 'zh' }))
  const completeExercise = (exerciseId: string) => setProgress((p) => { const completedExercisesNext = p.completedExercises.includes(exerciseId) ? p.completedExercises : [...p.completedExercises, exerciseId]; const lessonDone = selected.exercises.every((exercise) => completedExercisesNext.includes(exercise.id)); return { ...p, completedExercises: completedExercisesNext, completedLessons: lessonDone && !p.completedLessons.includes(selected.id) ? [...p.completedLessons, selected.id] : p.completedLessons } })
  return <div className="app-shell">
    <header className="topbar"><a className="brand" href="."><span className="brand-mark">S</span><span>Syntax<span className="muted-brand">Lab</span></span></a><div className="top-actions"><span className="progress-label">{completedCount} / {tomlModule.lessons.length} {t.lessons} · {completedExercises} / {tomlModule.lessons.length * 3} {t.exercises}</span><button className="text-button" onClick={toggleLocale}><Globe2 size={15} /> {t.lang}</button><button className="text-button" onClick={() => setShowAbout(true)}><Info size={15} /> {t.about}</button><button className="icon-button" aria-label="Toggle theme" onClick={() => setProgress((p) => ({ ...p, dark: !p.dark }))}>{progress.dark ? <Sun size={17} /> : <Moon size={17} />}</button><button className="menu-button" onClick={() => setMobileNav(!mobileNav)} aria-label="Open lessons"><Menu size={19} /></button></div></header>
    <div className="layout">
      <aside className={`sidebar ${mobileNav ? 'open' : ''}`}><div className="sidebar-head"><div><span className="overline">{t.path}</span><h2>{progress.locale === 'zh' && activeModule.id === computerModule.id ? '计算机二级' : activeModule.name}</h2></div><button className="close-mobile" onClick={() => setMobileNav(false)}><X size={17} /></button></div><div className="module-switcher"><button className={activeModule.id === 'toml' ? 'selected' : ''} onClick={() => selectModule('toml')}>TOML</button><button className={activeModule.id === computerModule.id ? 'selected' : ''} onClick={() => selectModule(computerModule.id)}>计算机二级入门</button></div><div className="progress-track"><span style={{ width: `${(completedCount / activeModule.lessons.length) * 100}%` }} /></div><div className="lesson-list">{activeModule.lessons.map((lesson) => { const lessonLocalized = progress.locale === 'zh' && activeModule.id === computerModule.id ? computerChinese[lesson.id] : lessonZh[lesson.id]; const done = progress.completedLessons.includes(`${activeModule.id}:${lesson.id}`) || (activeModule.id === 'toml' && progress.completedLessons.includes(lesson.id)); return <button className={`lesson-item ${selected.id === lesson.id ? 'active' : ''}`} key={lesson.id} onClick={() => selectLesson(lesson.id)}><span className="lesson-number">{lesson.number}</span><span className="lesson-title">{lessonLocalized?.title ?? lesson.title}</span>{done && <CircleCheck size={15} className="lesson-check" />}</button> })}</div><button className="reset-button" onClick={() => { if (confirm(progress.locale === 'zh' ? '确定重置 SyntaxLab 学习进度吗？' : 'Reset your SyntaxLab progress?')) setProgress({ ...defaultProgress, locale: progress.locale }) }}><RotateCcw size={14} /> {t.reset}</button></aside>
      <main className="main-content"><div className="content-wrap"><div className="breadcrumb"><span>SYNTAXLAB</span><ChevronRight size={13} /><span>{activeModule.language}</span><ChevronRight size={13} /><span className="current">{selected.number} / {activeModule.lessons.length.toString().padStart(2, '0')}</span></div><article className="lesson-content"><div className="eyebrow">{currentCopy?.eyebrow ?? computerCopy?.eyebrow ?? selected.eyebrow}</div><h1>{currentCopy?.title ?? computerCopy?.title ?? selected.title}</h1><p className="lead">{currentCopy?.summary ?? computerCopy?.summary ?? selected.summary}</p>{(localized?.sections ?? computerCopy?.sections ?? selected.sections).map((section) => <section key={section.heading}><h3>{section.heading}</h3><p>{section.body}</p></section>)}<div className="code-example"><div className="code-label"><Terminal size={14} /> {t.example}</div><pre><code>{selected.example}</code></pre></div>{(localized?.note ?? selected.note) && <div className="note"><Lightbulb size={16} /><span>{localized?.note ?? selected.note}</span></div>}<div className="lesson-complete"><button className={`complete-button ${isLessonComplete ? 'done' : ''}`} onClick={markLesson}>{isLessonComplete ? <><Check size={16} /> {t.completed}</> : t.complete}</button></div></article></div></main>
      <aside className="practice-panel"><div className="practice-head"><div><span className="overline">{t.practice}</span><h2>{t.write}</h2><small className="practice-count">{selected.exercises.filter((exercise) => progress.completedExercises.includes(exercise.id)).length} / {selected.exercises.length} {t.exercises}</small></div><Code2 size={20} className="practice-icon" /></div><div className="practice-scroll">{visibleExercises.map((exercise, index) => <ExerciseCard key={exercise.id} exercise={exercise} index={index} editor={activeModule.editor} completed={progress.completedExercises.includes(exercise.id)} onComplete={() => completeExercise(exercise.id)} t={t} locale={progress.locale} />)}</div></aside>
    </div><footer><button className="module-toggle" onClick={() => setShowModules(!showModules)}>{t.explore} <ChevronDown size={14} /></button>{showModules && <div className="module-popover"><strong>{t.soon}</strong><span>{t.soonDetail}</span><small>{progress.locale === 'zh' ? '点击左侧专栏即可切换学习路径，进度分别保存。' : 'Choose a module in the sidebar; progress is saved separately.'}</small></div>}<button className="footer-about" onClick={() => setShowAbout(true)}>{t.about}</button><span>SyntaxLab is open source · Learn by writing.</span></footer>{showAbout && <div className="modal-backdrop" onClick={() => setShowAbout(false)}><div className="about-modal" role="dialog" aria-modal="true" onClick={(event) => event.stopPropagation()}><div className="about-modal-head"><div className="brand"><span className="brand-mark">S</span><span>Syntax<span className="muted-brand">Lab</span></span></div><button className="icon-button" onClick={() => setShowAbout(false)} aria-label={t.close}><X size={17} /></button></div><h2>{t.aboutTitle}</h2><p>{t.aboutBody}</p><p className="about-detail">{t.aboutDetail}</p><a href="https://github.com/dsclca12/SyntaxLab" target="_blank" rel="noreferrer">GitHub repository ↗</a></div></div>}
  </div>
}

function ExerciseCard({ exercise, index, editor, completed, onComplete, t, locale }: { exercise: Exercise; index: number; editor: 'toml' | 'text'; completed: boolean; onComplete: () => void; t: typeof copy.zh | typeof copy.en; locale: Locale }) {
  const [value, setValue] = useState(exercise.starter)
  const [attempts, setAttempts] = useState(0)
  const [checked, setChecked] = useState(false)
  const [result, setResult] = useState<ReturnType<typeof parseToml> | null>(null)
  const [open, setOpen] = useState(index === 0)
  const check = () => { const parsed = editor === 'toml' ? parseToml(value) : { valid: true, data: value }; const next = parsed.valid && exercise.validate(parsed.data, value); setAttempts((a) => a + 1); setChecked(true); setResult(next ? { valid: true, data: parsed.data } : parsed); if (next) onComplete() }
  return <div className={`exercise ${open ? 'expanded' : ''} ${completed ? 'completed' : ''}`}><button className="exercise-summary" onClick={() => setOpen(!open)}><span className="exercise-index">0{index + 1}</span><span><strong>{exercise.title}</strong><small>{exercise.kind === 'complete' ? t.completeExample : exercise.kind === 'repair' ? t.repair : t.create}</small></span>{completed ? <CircleCheck size={17} className="success-icon" /> : open ? <ChevronDown size={17} /> : <ChevronRight size={17} />}</button>{open && <div className="exercise-body"><p>{exercise.prompt}</p><CodeMirror value={value} height="145px" extensions={editor === 'toml' ? [langs.toml()] : []} theme={document.documentElement.dataset.theme === 'dark' ? oneDark : undefined} onChange={setValue} basicSetup={{ lineNumbers: true, foldGutter: false }} /><div className="exercise-actions"><button className="check-button" onClick={check}><Check size={15} /> {t.check}</button><button className="clear-button" onClick={() => { setValue(exercise.starter); setChecked(false); setResult(null); setAttempts(0) }}>{t.resetAnswer}</button></div>{result && <div className={`result ${result.valid ? 'success' : 'error'}`}>{result.valid ? <><CircleCheck size={15} /><span>{t.correct}</span></> : <><X size={15} /><span>{friendlyError(result.error, locale)}</span></>}</div>}{checked && !result?.valid && attempts > 0 && <div className="hint"><Lightbulb size={15} /><span>{attempts >= 3 ? exercise.hints[2] : exercise.hints[attempts - 1]}</span></div>}{checked && !result?.valid && attempts >= 3 && <div className="answer-reveal"><strong>{locale === 'zh' ? '参考答案' : 'Reference answer'}</strong><pre>{exercise.solution}</pre></div>}</div>}</div>
}
export default App
